modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"
[[mods]]
modId="princess_delight"
version="0.0.1"
displayName="Princess Delight"
logoFile= ""
credits="Thanks your support"
authors="nami_zero"
description='''
something of princess connect:RE
'''
[[dependencies.princess_delight]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.princess_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
